[package]
name = "rust_dojo"
version = "0.0.1"
authors = ["tobi6112 <22715034+tobi6112@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
